> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.random.rand
function3 = np.arange
function4 = np.reshape
function5 = np.identity

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [7]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [8]:
# Example 2 - working
arr1=[[1,2],
     [5,6]]
arr2=[[11,2,3],
      
      [6,0,6]]
np.concatenate(arr1,arr2,axis=0)

TypeError: concatenate() got multiple values for argument 'axis'

Explanation about example

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2,4], 
        [3, 4,5]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

array([[ 1,  2,  4],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [10]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [11]:
# Example 1 - working
a=np.random.rand(3,10)
a

array([[0.50988116, 0.83213532, 0.84374527, 0.7192196 , 0.30975454,
        0.04958464, 0.16100724, 0.75983208, 0.63494661, 0.88146277],
       [0.36335668, 0.2827757 , 0.63864846, 0.00965785, 0.61247909,
        0.02184784, 0.0977254 , 0.32426671, 0.42286225, 0.12245266],
       [0.45769212, 0.04365283, 0.83528347, 0.15865066, 0.61291271,
        0.14741846, 0.24993685, 0.92855852, 0.66280318, 0.24920465]])

Explanation about example

In [12]:
# Example 2 - working
x=np.array([45,78,97])
y=np.array([78,98,97])
np.arange(3,2)

array([], dtype=int64)

Explanation about example

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([7,8,9,7,8])
for i in a:
    print(i)

7
8
9
7
8


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [14]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [15]:
# Example 1 - working
a=np.array([1,2,5,4,6,7,8,9])
a[::-1]

array([9, 8, 7, 6, 4, 5, 2, 1])

Explanation about example

In [16]:
# Example 2 - working
a=np.array([45,78,78,94,75,85])
b=np.array([34,45,12,78,12,45])
a.reshape(3,2)
b.reshape(2,3)

array([[34, 45, 12],
       [78, 12, 45]])

Explanation about example

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([9,8,7,65,45,4,5])
b=a**2
print(a)
    


[ 9  8  7 65 45  4  5]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [19]:
# Example 1 - working
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


Explanation about example

In [20]:
# Example 2 - working
a=np.array([1,2,3,4,5,2,3,2,2])
for i in a:
    b=[]
    res=b.count(2)
    print(res)

0
0
0
0
0
0
0
0
0


Explanation about example

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.empty([2,2],dtype=int)
print(a)

[[4607182418800017408 4611686018427387904]
 [4613937818241073152 4616189618054758400]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [23]:
# Example 1 - working
np.identity(3,dtype=None)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Explanation about example

In [24]:
# Example 2 - working
np.core.records.array(a)

rec.array([[4607182418800017408, 4611686018427387904],
           [4613937818241073152, 4616189618054758400]],
          dtype=int64)

Explanation about example

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.tri(9,5,7)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vinodkumar-123/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/vinodkumar-123/numpy-array-operations


'https://jovian.com/vinodkumar-123/numpy-array-operations'